// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhfHqIeRkiv5rP1fq69FIDytjZNeIqFo',
    appId: '1:452492589286:web:07fa0be7dbdcc7e7fba327',
    messagingSenderId: '452492589286',
    projectId: 'cpi-app-2023',
    authDomain: 'cpi-app-2023.firebaseapp.com',
    storageBucket: 'cpi-app-2023.appspot.com',
    measurementId: 'G-KLBQFEHY15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Eomq8YY_tyVzFoU3t3DHvwVyhTXEI5E',
    appId: '1:452492589286:android:e99596b3d1a2eb8dfba327',
    messagingSenderId: '452492589286',
    projectId: 'cpi-app-2023',
    storageBucket: 'cpi-app-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXollWJc5ww9E8VF0aTkkIeGzZ-Rxo7g',
    appId: '1:452492589286:ios:e90f7717ac7825ccfba327',
    messagingSenderId: '452492589286',
    projectId: 'cpi-app-2023',
    storageBucket: 'cpi-app-2023.appspot.com',
    iosClientId: '452492589286-8ddfaavg5rnn1rhs2pg8tfo8v2ndbtp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYXollWJc5ww9E8VF0aTkkIeGzZ-Rxo7g',
    appId: '1:452492589286:ios:e90f7717ac7825ccfba327',
    messagingSenderId: '452492589286',
    projectId: 'cpi-app-2023',
    storageBucket: 'cpi-app-2023.appspot.com',
    iosClientId: '452492589286-8ddfaavg5rnn1rhs2pg8tfo8v2ndbtp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpiApp',
  );
}
